# build here
CC = gcc
FLAGS = -Wall -std=c11 -o
EXK = potatoe
SRC = main.c
OUTP = outputz.txt

raw :
	clear
	rm -f $(EXC)
	$(CC) $(FLAGS) $(EXK) $(SRC)
	@echo "[ $(EXK) ] is compiled and ready to run"

clean :
	clear
	rm -f $(EXC)
	rm -f $(OUTP)
	@echo "executable and outputs were deleted"
